### ISSUE TITLE
Deleting osint source not possible

### ISSUE THREAD

**Issue by Zeik0s** [taranis-ai/taranis-ai#223]
I built the containers on tag 0.9.1, imported the example feeds and wanted to delete one, but it failed with these messages: 

<details>
<summary>Core error message</summary>

```
core-1       | [Core] [INFO] - Schedule for source f8507729-43bd-4050-b380-de375195f040 removed
core-1       | [Core] [WARNING] - IntegrityError: update or delete on table "osint_source" violates foreign key constraint "news_item_osint_source_id_fkey" on table "news_item"
core-1       | DETAIL:  Key (id)=(f8507729-43bd-4050-b380-de375195f040) is still referenced from table "news_item".
core-1       |
core-1       | [Core] [ERROR] - Exception on /api/config/osint-sources/f8507729-43bd-4050-b380-de375195f040 [DELETE]
core-1       | Traceback (most recent call last):
core-1       |   File "/app/.venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
core-1       |     response = self.full_dispatch_request()
core-1       |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
core-1       |   File "/app/.venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
core-1       |     rv = self.handle_user_exception(e)
core-1       |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
core-1       |   File "/app/.venv/lib/python3.12/site-packages/flask_cors/extension.py", line 178, in wrapped_function
core-1       |     return cors_after_request(app.make_response(f(*args, **kwargs)))
core-1       |                                                 ^^^^^^^^^^^^^^^^^^
core-1       |   File "/app/.venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
core-1       |     rv = self.dispatch_request()
core-1       |          ^^^^^^^^^^^^^^^^^^^^^^^
core-1       |   File "/app/.venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
core-1       |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
core-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
core-1       |   File "/app/.venv/lib/python3.12/site-packages/flask/views.py", line 110, in view
core-1       |     return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
core-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
core-1       |   File "/app/.venv/lib/python3.12/site-packages/flask/views.py", line 191, in dispatch_request
core-1       |     return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
core-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
core-1       |   File "/app/core/managers/auth_manager.py", line 99, in wrapper
core-1       |     return fn(*args, **kwargs)
core-1       |            ^^^^^^^^^^^^^^^^^^^
core-1       |   File "/app/core/api/config.py", line 408, in delete
core-1       |     return {"message": f"OSINT Source {source.name} deleted", "id": f"{source_id}"}, 200
core-1       |                                        ^^^^^^^^^^^
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 566, in __get__
core-1       |     return self.impl.get(state, dict_)  # type: ignore[no-any-return]
core-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 1086, in get
core-1       |     value = self._fire_loader_callables(state, key, passive)
core-1       |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 1116, in _fire_loader_callables
core-1       |     return state._load_expired(state, passive)
core-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 796, in _load_expired
core-1       |     self.manager.expired_attribute_loader(self, toload, passive)
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 1670, in load_scalar_attributes
core-1       |     result = load_on_ident(
core-1       |              ^^^^^^^^^^^^^^
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 509, in load_on_ident
core-1       |     return load_on_pk_identity(
core-1       |            ^^^^^^^^^^^^^^^^^^^^
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 694, in load_on_pk_identity
core-1       |     session.execute(
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2351, in execute
core-1       |     return self._execute_internal(
core-1       |            ^^^^^^^^^^^^^^^^^^^^^^^
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2226, in _execute_internal
core-1       |     conn = self._connection_for_bind(bind)
core-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2095, in _connection_for_bind
core-1       |     return trans._connection_for_bind(engine, execution_options)
core-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
core-1       |   File "<string>", line 2, in _connection_for_bind
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 103, in _go
core-1       |     self._raise_for_prerequisite_state(fn.__name__, current_state)
core-1       |   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 973, in _raise_for_prerequisite_state
core-1       |     raise sa_exc.PendingRollbackError(
core-1       | sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.ForeignKeyViolation) update or delete on table "osint_source" violates foreign key constraint "news_item_osint_source_id_fkey" on table "news_item"
core-1       | DETAIL:  Key (id)=(f8507729-43bd-4050-b380-de375195f040) is still referenced from table "news_item".
core-1       |
core-1       | [SQL: DELETE FROM osint_source WHERE osint_source.id = %(id)s]
core-1       | [parameters: {'id': 'f8507729-43bd-4050-b380-de375195f040'}]
core-1       | (Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
```
</details>

Does this error mean every news item of the osint source has to be assessed before it can be deleted?

**Comment by b3n4kh** [comment]
I introduced a fix for this with: [c174d33](https://github.com/taranis-ai/taranis-ai/commit/c174d33a229911de6624b16ecf5df1f86da269fb)

With this fix, OSINT-Sources where News Items were already gathered can be deleted. 
This requires deleting all News Items gathered from this source as well. If this is the case, the user is presented with a Dialog prompting for confirmation.

Since sources are one of the main ways for fine-grained RBAC rules, to prevent an accidental data leak, this is the only way to manage this right now.
If necessary, a feature could be added that allows "reassigning" the existing News Items.

![image](https://github.com/taranis-ai/taranis-ai/assets/6696618/85b192d5-75d5-4a89-acb3-632411133af4)
