### ISSUE TITLE
Error when loading wordlist  from URL

### ISSUE THREAD

**Issue by Mar8x** [taranis-ai/taranis-ai#369]
### config 
- using github provided compose fil
```
ghcr.io/taranis-ai/taranis-gui         latest      0b0c3b727cbb   7 days ago      208MB
ghcr.io/taranis-ai/taranis-core        latest      2d69a3dd9d4e   2 weeks ago     308MB
ghcr.io/taranis-ai/taranis-worker      latest      9714ed8e2c69   2 weeks ago     11.4GB
ghcr.io/taranis-ai/taranis-scheduler   latest      776da9b47a4e   7 weeks ago     164MB
ghcr.io/taranis-ai/sse-broker          latest      c654da3e977a   8 weeks ago     1.03GB
ghcr.io/taranis-ai/rabbitmq            latest      192a54138f1d   2 months ago    179MB
```

### reproduce 
wordlist > new item > 
Fill in:
- Name
- description
- URL
- select tagging bot
 --> submit

```
[2024-11-27 09:26:17,853] ERROR in app: Exception on /api/config/word-lists [POST]
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/flask/views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/core/managers/auth_manager.py", line 90, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/app/core/api/config.py", line 530, in post
    wordlist = word_list.WordList.add(request.json)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/core/model/base_model.py", line 64, in add
    item = cls.from_dict(data)
           ^^^^^^^^^^^^^^^^^^^
  File "/app/core/model/base_model.py", line 85, in from_dict
    return cls(**data)
           ^^^^^^^^^^^
TypeError: __init__() got an unexpected keyword argument 'items'

```
### alternative
Downloading the json and doing an import works without issues.

**Comment by not4Pedro** [comment]
Hi, thank you for the issue, there is a bug at the moment, we will work on fixing it, sorry for that.

As a workaround, just like you mentioned, you can be adding wordlists by importing them. Just stick to the format in [default_word_lists.json](https://github.com/taranis-ai/taranis-ai/blob/master/src/core/core/static/default_word_lists.json)

**Comment by b3n4kh** [comment]
There seems to be an issue between the payload sent by: [WordListForm](https://github.com/taranis-ai/taranis-ai/blob/master/src/gui/src/components/config/WordListForm.vue) and [word_list.py __init__](https://github.com/taranis-ai/taranis-ai/blob/master/src/core/core/model/word_list.py#L32)
