### ISSUE TITLE
RSS bot doesn't accept 'hourly'

### ISSUE THREAD

**Issue by kamil-certat** [taranis-ai/taranis-ai#383]
When configuring an RSS Bot to collect a source hourly, the[ documented value](https://taranis.ai/docs/admin/bots/#bot's-settings) `hourly` has caused an error. Stack trace:

```
[2024-12-12 10:47:33,282] ERROR in app: Exception on /api/config/osint-sources [POST]
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/flask/views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/core/managers/auth_manager.py", line 90, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/app/core/api/config.py", line 373, in post
    if source := osint_source.OSINTSource.add(request.json):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/core/model/osint_source.py", line 147, in add
    osint_source.schedule_osint_source()
  File "/app/core/model/osint_source.py", line 218, in schedule_osint_source
    entry = self.to_task_dict()
            ^^^^^^^^^^^^^^^^^^^
  File "/app/core/model/osint_source.py", line 132, in to_task_dict
    "jobs_params": {"trigger": "interval", "minutes": int(self.get_schedule()), "max_instances": 1},
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'hourly'
```

**Comment by not4Pedro** [comment]
Thank you for the isssue.
#### early triage:
The documentation stems from https://github.com/taranis-ai/taranis.ai/issues/15.

the conversion from strings was there before https://github.com/taranis-ai/taranis-ai/blob/d62122dec6b9d6d54ca40bb29a22073fc413951a/src/core/core/model/queue.py#L81

We need to check further for the Bots scheduling.

**Comment by llinauer** [comment]
This was fixed by by https://github.com/taranis-ai/taranis-ai/pull/402
Bots and Collectors now accept the REFRESH_INTERVALs: "hourly", "daily" & "weekly" as well.
