### ISSUE TITLE
TypeError in handling WordList update results

### ISSUE THREAD

**Issue by kamil-certat** [taranis-ai/taranis-ai#384]
I see a stack trace in logs, I cannot say what exactly was the action causing it - looks like an internal callback after triggering collecting word lists

```
[2024-12-12 09:00:08,502] ERROR in app: Exception on /api/tasks/ [POST]
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/flask/views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/core/managers/auth_manager.py", line 118, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/app/core/api/task.py", line 35, in post
    WordList.update_word_list(**result)
TypeError: WordList.update_word_list() got an unexpected keyword argument 'exc_type'
```

**Comment by llinauer** [comment]
When the gather_word_list celery task catches an exception (of any kind), it returns a dict containing the "exc_type", "exc_message" and "exc_module" as the result.

This dict is then passed to WordList.update_word_list as **result, and of course the update_word_list function has no "exc_type" argument causing the TypeError.

With PR https://github.com/taranis-ai/taranis-ai/pull/417, we introduced cleaner exception handling for failed Celery tasks.
The exception will be caught and instead, you will see the reason for the task failing in the log.
For example:

![Image](https://github.com/user-attachments/assets/48f251ee-41a2-448c-aa50-f603eaaea91e)
